name: Python CI Pipeline hello-world
on: push
jobs:
  build-push-dockerimage;
    runs-on:ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.1.2
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
        run:echo "Hello World!"
