name: Python CI Pipeline hello-world
on: push
jobs:
  build-push-dockerimage:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.1.2
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Login
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-image:latest .
      - name: Docker Image 
        run: docker iamges
      - name: Docker Push 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/python-image:latest
          
          
